version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: bytes
    versions:
    - ">= 0"
  - dependency-name: libsqlite3-sys
    versions:
    - ">= 0"
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.63
  - dependency-name: tracing
    versions:
    - 0.1.22
    - 0.1.23
    - 0.1.24
  - dependency-name: paste
    versions:
    - 1.0.4
  - dependency-name: async-trait
    versions:
    - 0.1.42
  - dependency-name: proc-macro2
    versions:
    - 1.0.24
- package-ecosystem: npm
  directory: "/api_tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependencies
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: ethers
    versions:
    - 5.0.26
    - 5.0.27
    - 5.0.28
    - 5.0.29
    - 5.0.30
    - 5.0.31
    - 5.0.32
    - 5.1.0
    - 5.1.3
  - dependency-name: ajv
    versions:
    - 7.0.3
    - 7.0.4
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.3
    - 8.0.1
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
    - 4.2.15
    - 4.2.16
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: jasmine
    versions:
    - 3.6.4
